joy_node:
  ros__parameters:
    device_id : 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 0
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0
    
    axis_angular:
      z: 1
    scale_angular:
      z: 0.5
    scale_angular_turbo:
      z: 1.0

enable_button: 1
enable_turbo_button: 2

require_enable_button: true